### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by kevinwaxi** [ferdiansyah0611/system_information_school#10]
Error 

  Class "App\models\ScNote" not found

  at database/seeds/ScNoteSeeder.php:15
    11|      */
    12|     public function run()
    13|     {
    14|         for ($i=1; $i < 11; $i++) {
  > 15|             ScNote::create([
    16|             	'user_id' => $i,
    17|             	'title' => 'My Notes',
    18|             	'note' => 'Laravel is modern framework php'
    19|             ]);

      +7 vendor frames 
  8   database/seeds/DatabaseSeeder.php:18
      Illuminate\Database\Seeder::call()

      +19 vendor frames 
  28  app/Console/Commands/Application.php:92
      Illuminate\Console\Command::call()

**Comment by ferdiansyah0611** [comment]
Only typo. change App\models\ScNote to App\Models\ScNote
[Solved](https://github.com/ferdiansyah0611/system_information_school/commit/140cc456b5674513d56d128a6f5f551415cb2000)
